package DataStructures.Arrays.Techniques.PrefixSum;

public class EvenSumSubArrays {

    /// Problem:
    /// Count how many sub arrays have an even sum.

    /**
     * Time Complexity: O(n)
     * For explanation, we can try ChatGPT to explain this code as it is checked and generated by it.
     * */
    private static int countEvenSumSubArrays(int[] arr) {
        int count = 0;
        int prefixSum = 0;
        int even = 1;
        int odd = 0;

        for (int num: arr) {
            prefixSum += num;

            if (prefixSum % 2 == 0) {
                count += even;
                even++;
            } else {
                count += odd;
                odd++;
            }
        }

        return count;
    }

    public static void main(String[] args) {
        int[] arr = {1, 2, 3, 4};

        System.out.println(countEvenSumSubArrays(arr));
    }

}
